/**
 * Cheesy Arena `/reports/*` surface: the CSV and PDF report endpoints CA exposes for FTAs and event
 * staff (web/reports.go, web/web.go lines ~188-202). Reads the fake-fms FmsStore and reproduces CA's
 * report content.
 *
 * Accuracy notes:
 *  - The CSV reports reproduce CA's `templates/*.csv` column layout, field order, quoting and trailing
 *    bytes exactly (the templates build the CSV inline; there is no header/library involved), mapping
 *    each CA data field onto its fake-fms store equivalent.
 *  - The PDF reports are generated by a tiny hand-rolled single/multi-page PDF writer (base-14
 *    Helvetica, no font embedding). They are valid PDFs containing the same title + tabular data CA's
 *    gofpdf output carries, but are not a byte-for-byte reproduction of CA's gofpdf layout.
 *  - Time values are rendered in UTC (the emulator has no notion of the CA host's local timezone);
 *    CA formats these in the field's local time.
 *
 * Pure and self-contained: only "shared" types and the FmsStore type are imported. No side effects.
 */
import type { FmsState, RankingRecord, ScheduleEntry, TournamentLevel } from "shared";
import type { FmsStore } from "../state/store";

// #region small helpers

const CORS = "Access-Control-Allow-Origin";
const MM_TO_PT = 2.834645; // CA lays out report tables in millimetres; scale to PDF points.

function pad2(n: number): string {
	return String(n).padStart(2, "0");
}

const WEEKDAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

/** Reproduce Go's default `time.Time.String()` (what `{{.Time.Local}}` prints), in UTC. */
function goTimeString(iso: string): string {
	const d = new Date(iso);
	if (Number.isNaN(d.getTime())) return iso;
	return (
		`${d.getUTCFullYear()}-${pad2(d.getUTCMonth() + 1)}-${pad2(d.getUTCDate())} ` +
		`${pad2(d.getUTCHours())}:${pad2(d.getUTCMinutes())}:${pad2(d.getUTCSeconds())} +0000 UTC`
	);
}

/** Go time layout "03:04 PM" (12-hour, zero-padded), in UTC. */
function fmtClock(iso: string | null): string {
	if (!iso) return "";
	const d = new Date(iso);
	if (Number.isNaN(d.getTime())) return "";
	const h = d.getUTCHours();
	const h12 = h % 12 === 0 ? 12 : h % 12;
	return `${pad2(h12)}:${pad2(d.getUTCMinutes())} ${h < 12 ? "AM" : "PM"}`;
}

/** Go time layout "1/02 03:04 PM" (month no pad, day padded), in UTC. */
function fmtMonthDayClock(iso: string | null): string {
	if (!iso) return "";
	const d = new Date(iso);
	if (Number.isNaN(d.getTime())) return "";
	return `${d.getUTCMonth() + 1}/${pad2(d.getUTCDate())} ${fmtClock(iso)}`;
}

/** Go time layout "Mon 1/02 03:04 PM", in UTC. */
function fmtWeekdayMonthDayClock(iso: string | null): string {
	if (!iso) return "";
	const d = new Date(iso);
	if (Number.isNaN(d.getTime())) return "";
	return `${WEEKDAYS[d.getUTCDay()]} ${fmtMonthDayClock(iso)}`;
}

/** Reproduce Go's `time.Duration.String()` truncated to whole seconds (e.g. 90 -> "1m30s"). */
function goDuration(totalSec: number): string {
	if (totalSec === 0) return "0s";
	const neg = totalSec < 0;
	let s = Math.abs(Math.trunc(totalSec));
	const h = Math.floor(s / 3600);
	s -= h * 3600;
	const m = Math.floor(s / 60);
	s -= m * 60;
	let out: string;
	if (h > 0) out = `${h}h${m}m${s}s`;
	else if (m > 0) out = `${m}m${s}s`;
	else out = `${s}s`;
	return (neg ? "-" : "") + out;
}

function levelTypeName(level: TournamentLevel): string {
	switch (level) {
		case "Practice":
			return "Practice";
		case "Qualification":
			return "Qualification";
		case "Playoff":
			return "Playoff";
		default:
			return "Test";
	}
}

/** CA short match name (matches the fake-fms CA projector: quals Q#, playoff M#, finals F#). */
function shortName(level: TournamentLevel, matchNumber: number): string {
	switch (level) {
		case "Practice":
			return `P${matchNumber}`;
		case "Qualification":
			return `Q${matchNumber}`;
		case "Playoff":
			return matchNumber >= 14 ? `F${matchNumber - 13}` : `M${matchNumber}`;
		default:
			return "T";
	}
}

/** /reports/{...}/{type} token -> level, or null if invalid (CA answers invalid with a 500). */
const TYPE_LEVELS: Record<string, TournamentLevel> = {
	test: "None",
	practice: "Practice",
	qualification: "Qualification",
	playoff: "Playoff",
};

function matchesForLevel(state: FmsState, level: TournamentLevel): ScheduleEntry[] {
	return state.schedule.filter((e) => e.level === level).sort((a, b) => a.matchNumber - b.matchNumber);
}

function sortedRankings(state: FmsState): RankingRecord[] {
	return [...state.rankings].sort((a, b) => a.rank - b.rank);
}

function sortedTeams(state: FmsState): FmsState["teams"] {
	return [...state.teams].sort((a, b) => a.number - b.number);
}

function teamName(state: FmsState, number: number): string {
	return state.teams.find((t) => t.number === number)?.name ?? "";
}

/** CA maps a ranking's CSV/PDF columns from these store-derived values (see the CA projector). */
function rankingPoints(r: RankingRecord): number {
	return Math.round(r.rankingScore * r.matchesPlayed);
}

// #endregion

// #region Response builders

function csvResponse(body: string): Response {
	// CA deliberately serves report CSVs as text/plain so browsers show them rather than downloading.
	return new Response(body, { status: 200, headers: { "Content-Type": "text/plain", [CORS]: "*" } });
}

function pdfResponse(bytes: Uint8Array<ArrayBuffer>): Response {
	return new Response(bytes, { status: 200, headers: { "Content-Type": "application/pdf", [CORS]: "*" } });
}

function serverError(detail: string): Response {
	// Mirror CA's handleWebErr: http.Error with "Internal server error: <err>\n", status 500.
	return new Response(`Internal server error: ${detail}\n`, {
		status: 500,
		headers: { "Content-Type": "text/plain; charset=utf-8", [CORS]: "*" },
	});
}

// #endregion

// #region CSV reports (reproduce templates/*.csv exactly)

/** Join CA-template rows: header line, one newline-terminated row per record, then a trailing newline. */
function csvBody(header: string, rows: string[]): string {
	return `${header}\n${rows.map((r) => `${r}\n`).join("")}\n`;
}

function rankingsCsv(state: FmsState): Response {
	const header =
		"Rank,TeamId,RankingPoints,MatchPoints,AutoFuelPoints,TowerPoints,Wins,Losses,Ties,Disqualifications,Played";
	const rows = sortedRankings(state).map(
		(r) =>
			`${r.rank},${r.teamNumber},${rankingPoints(r)},${r.sort2},${r.sort3},${r.sort4},` +
			`${r.wins},${r.losses},${r.ties},0,${r.matchesPlayed}`,
	);
	return csvResponse(csvBody(header, rows));
}

/**
 * Partition the ranked teams into picked / backup sets from the alliances, exactly as CA's
 * findBackupTeams does: alliance members (captain + picks) are removed; a fourth alliance member (the
 * alternate) is a backup that has been "called". Returns null when no alliances exist (CA errors).
 */
function backupPartition(state: FmsState): { picked: Set<number>; calledBackups: Set<number> } | null {
	if (state.alliances.length === 0) return null;
	const picked = new Set<number>();
	const calledBackups = new Set<number>();
	for (const a of state.alliances) {
		for (const n of [a.captainTeamNumber, a.firstRoundTeamNumber, a.secondRoundTeamNumber]) {
			if (n) picked.add(n);
		}
		if (a.alternateTeamNumber) calledBackups.add(a.alternateTeamNumber);
	}
	return { picked, calledBackups };
}

function backupsCsv(state: FmsState): Response {
	const part = backupPartition(state);
	if (!part) return serverError("backup teams report is unavailable until alliances have been selected");
	const rows = sortedRankings(state)
		.filter((r) => !part.picked.has(r.teamNumber))
		.map((r) => `${r.rank},${part.calledBackups.has(r.teamNumber)},${r.teamNumber},${rankingPoints(r)}`);
	return csvResponse(csvBody("Rank,Called,TeamId,RankingPoints", rows));
}

function scheduleCsv(state: FmsState, level: TournamentLevel): Response {
	const header =
		"Match,Type,Time,Red1,Red1IsSurrogate,Red2,Red2IsSurrogate,Red3,Red3IsSurrogate," +
		"Blue1,Blue1IsSurrogate,Blue2,Blue2IsSurrogate,Blue3,Blue3IsSurrogate";
	const type = levelTypeName(level);
	const rows = matchesForLevel(state, level).map((e) => {
		const [r1, r2, r3] = e.red;
		const [b1, b2, b3] = e.blue;
		// The store does not model surrogates, so every IsSurrogate column is false.
		return (
			`${shortName(e.level, e.matchNumber)},${type},${goTimeString(e.scheduledStartTime)},` +
			`${r1},false,${r2},false,${r3},false,${b1},false,${b2},false,${b3},false`
		);
	});
	return csvResponse(csvBody(header, rows));
}

function teamsCsv(state: FmsState): Response {
	const header = "Number,Name,Nickname,SchoolName,City,StateProv,Country,RookieYear,RobotName,HasConnected";
	// The store only carries a team number + display name; the remaining CA columns have no source.
	const rows = sortedTeams(state).map((t) => `${t.number},"${t.name}","${t.name}","","","","",0,"",false`);
	return csvResponse(csvBody(header, rows));
}

function ftaCsv(state: FmsState): Response {
	// The store has no per-team HasConnected/FtaNotes; CA's template also emits a trailing ",," line.
	const rows = sortedTeams(state).map((t) => `${t.number},false,`);
	return csvResponse(`Number,HasConnected,FtaNotes\n${rows.map((r) => `${r}\n`).join("")},,\n`);
}

function wpaKeysCsv(state: FmsState): Response {
	// CA serves this one as an attachment (text/csv) with CRLF line endings and no header row.
	const body = sortedTeams(state)
		.map((t) => `${t.number},${t.wpaKey}\r\n`)
		.join("");
	return new Response(body, {
		status: 200,
		headers: {
			"Content-Type": "text/csv",
			"Content-Disposition": "attachment; filename=keys.csv",
			[CORS]: "*",
		},
	});
}

// #endregion

// #region minimal PDF writer

interface PdfItem {
	x: number;
	y: number;
	size: number;
	bold: boolean;
	text: string;
}
interface PdfPage {
	items: PdfItem[];
}

/** Escape a string for a PDF literal string, dropping anything outside single-byte range. */
function escapePdfText(s: string): string {
	let out = "";
	for (const ch of s) {
		const code = ch.codePointAt(0) ?? 63;
		if (code > 255) {
			out += "?";
		} else if (ch === "\\" || ch === "(" || ch === ")") {
			out += `\\${ch}`;
		} else if (code < 32) {
			out += " ";
		} else {
			out += ch;
		}
	}
	return out;
}

function fmtCoord(n: number): string {
	return Number.isInteger(n) ? String(n) : n.toFixed(2);
}

/**
 * Assemble a valid PDF from pre-laid-out text items. Two base-14 fonts are registered (Helvetica and
 * Helvetica-Bold); no glyphs are embedded. All bytes stay within Latin-1 so string length equals byte
 * length, which keeps the cross-reference offsets correct.
 */
function buildPdf(pages: PdfPage[]): Uint8Array<ArrayBuffer> {
	const parts: string[] = [];
	const offsets: number[] = [];
	let cursor = 0;
	const push = (s: string): void => {
		parts.push(s);
		cursor += s.length;
	};
	const addObj = (num: number, body: string): void => {
		offsets[num] = cursor;
		push(`${num} 0 obj\n${body}\nendobj\n`);
	};

	push("%PDF-1.4\n");

	const pageObjNums = pages.map((_, i) => 5 + i * 2);
	addObj(1, "<< /Type /Catalog /Pages 2 0 R >>");
	addObj(2, `<< /Type /Pages /Kids [${pageObjNums.map((n) => `${n} 0 R`).join(" ")}] /Count ${pages.length} >>`);
	addObj(3, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>");
	addObj(4, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>");

	pages.forEach((page, i) => {
		const pageNum = 5 + i * 2;
		const contentNum = 6 + i * 2;
		let content = "";
		for (const it of page.items) {
			content +=
				`BT /F${it.bold ? 2 : 1} ${it.size} Tf ${fmtCoord(it.x)} ${fmtCoord(it.y)} Td ` +
				`(${escapePdfText(it.text)}) Tj ET\n`;
		}
		addObj(
			pageNum,
			"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] " +
				`/Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentNum} 0 R >>`,
		);
		addObj(contentNum, `<< /Length ${content.length} >>\nstream\n${content}endstream`);
	});

	const totalObjs = 4 + pages.length * 2;
	const xrefOffset = cursor;
	let xref = `xref\n0 ${totalObjs + 1}\n0000000000 65535 f \n`;
	for (let n = 1; n <= totalObjs; n++) {
		xref += `${String(offsets[n] ?? 0).padStart(10, "0")} 00000 n \n`;
	}
	push(xref);
	push(`trailer\n<< /Size ${totalObjs + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`);

	// Encode as single-byte (Latin-1): every char is already <= 255, so byte length == string length,
	// which is what keeps the xref offsets (computed above from string length) correct.
	const bin = parts.join("");
	const bytes = new Uint8Array(bin.length);
	for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i) & 0xff;
	return bytes;
}

// PDF page/table geometry (US Letter, in points).
const PAGE_TOP = 756;
const PAGE_BOTTOM = 48;
const LEFT_MARGIN = 36;
const LINE_HEIGHT = 15;
const BODY_SIZE = 9;
const TITLE_SIZE = 13;

interface Column {
	header: string;
	x: number;
}

/** Build columns from CA-style [header, widthMm] pairs, cumulative from the left margin. */
function columns(defs: [string, number][]): Column[] {
	const cols: Column[] = [];
	let x = LEFT_MARGIN;
	for (const [header, wMm] of defs) {
		cols.push({ header, x: x + 2 });
		x += wMm * MM_TO_PT;
	}
	return cols;
}

/**
 * Lay out a titled table across as many US-Letter pages as needed. The title is drawn once (first
 * page); the column header row repeats on every page. An optional footer line is appended at the end.
 */
function tablePdf(title: string, cols: Column[], rows: string[][], footer?: string): Uint8Array<ArrayBuffer> {
	const pages: PdfPage[] = [];
	let items: PdfItem[] = [];
	let y = 0;

	const newPage = (withTitle: boolean): void => {
		items = [];
		y = PAGE_TOP;
		if (withTitle) {
			items.push({ x: LEFT_MARGIN, y, size: TITLE_SIZE, bold: true, text: title });
			y -= TITLE_SIZE + 8;
		}
		// Column header row.
		for (const c of cols) items.push({ x: c.x, y, size: BODY_SIZE, bold: true, text: c.header });
		y -= LINE_HEIGHT;
	};
	const finishPage = (): void => {
		pages.push({ items });
	};

	newPage(true);
	for (const row of rows) {
		if (y < PAGE_BOTTOM) {
			finishPage();
			newPage(false);
		}
		for (let i = 0; i < cols.length; i++) {
			const c = cols[i];
			if (!c) continue;
			items.push({ x: c.x, y, size: BODY_SIZE, bold: false, text: row[i] ?? "" });
		}
		y -= LINE_HEIGHT;
	}
	if (footer) {
		if (y < PAGE_BOTTOM) {
			finishPage();
			newPage(false);
		}
		items.push({ x: LEFT_MARGIN, y: y - 4, size: BODY_SIZE, bold: false, text: footer });
	}
	finishPage();
	return buildPdf(pages);
}

/** CA's addTimeGeneratedFooter, rendered in UTC. */
function generatedFooter(): string {
	const now = new Date();
	const h = now.getUTCHours();
	const h12 = h % 12 === 0 ? 12 : h % 12;
	const time = `${h12}:${pad2(now.getUTCMinutes())}:${pad2(now.getUTCSeconds())} ${h < 12 ? "AM" : "PM"}`;
	const MON = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
	const date = `${WEEKDAYS[now.getUTCDay()]} ${MON[now.getUTCMonth()]} ${now.getUTCDate()} ${now.getUTCFullYear()}`;
	return `Report generated at ${time} on ${date}`;
}

// #endregion

// #region PDF reports

function rankingsPdf(state: FmsState): Response {
	const cols = columns([
		["Rank", 13],
		["Team", 20],
		["RP", 24],
		["Match", 24],
		["Auto Fuel", 24],
		["Tower", 24],
		["W-L-T", 26],
		["DQ", 20],
		["Played", 20],
	]);
	const rows = sortedRankings(state).map((r) => [
		String(r.rank),
		String(r.teamNumber),
		String(rankingPoints(r)),
		String(r.sort2),
		String(r.sort3),
		String(r.sort4),
		`${r.wins}-${r.losses}-${r.ties}`,
		"0",
		String(r.matchesPlayed),
	]);
	return pdfResponse(tablePdf(`Team Standings - ${state.event.name}`, cols, rows, generatedFooter()));
}

function backupsPdf(state: FmsState): Response {
	const part = backupPartition(state);
	if (!part) return serverError("backup teams report is unavailable until alliances have been selected");
	const cols = columns([
		["Rank", 13],
		["Called?", 22],
		["Team", 22],
		["RP", 23],
	]);
	const rows = sortedRankings(state)
		.filter((r) => !part.picked.has(r.teamNumber))
		.map((r) => [
			String(r.rank),
			part.calledBackups.has(r.teamNumber) ? "Y" : "",
			String(r.teamNumber),
			String(rankingPoints(r)),
		]);
	return pdfResponse(tablePdf(`Backup Teams - ${state.event.name}`, cols, rows, generatedFooter()));
}

function schedulePdf(state: FmsState, level: TournamentLevel): Response {
	const cols = columns([
		["Time", 35],
		["Match", 40],
		["Red 1", 20],
		["Red 2", 20],
		["Red 3", 20],
		["Blue 1", 20],
		["Blue 2", 20],
		["Blue 3", 20],
	]);
	const matches = matchesForLevel(state, level);
	const team = (n: number): string => (n === 0 ? "" : String(n));
	const rows = matches.map((e) => [
		fmtWeekdayMonthDayClock(e.scheduledStartTime),
		e.description || `${e.level} ${e.matchNumber}`,
		team(e.red[0]),
		team(e.red[1]),
		team(e.red[2]),
		team(e.blue[0]),
		team(e.blue[1]),
		team(e.blue[2]),
	]);
	let footer = generatedFooter();
	if (level !== "Playoff") {
		const matchesPerTeam = state.teams.length > 0 ? Math.floor((matches.length * 6) / state.teams.length) : 0;
		footer = `Matches Per Team: ${matchesPerTeam}    ${footer}`;
	}
	return pdfResponse(tablePdf(`Match Schedule - ${state.event.name}`, cols, rows, footer));
}

function teamsPdf(state: FmsState): Response {
	const cols = columns([
		["Team", 12],
		["Name", 80],
		["Location", 80],
		["Rookie Year", 23],
	]);
	// Location is CA's "City, StateProv, Country"; the store carries none, so it is always ", , ".
	const rows = sortedTeams(state).map((t) => [String(t.number), t.name, ", , ", "0"]);
	return pdfResponse(tablePdf(`Team List - ${state.event.name}`, cols, rows, generatedFooter()));
}

function cyclePdf(state: FmsState, level: TournamentLevel): Response {
	const cols = columns([
		["Match", 15],
		["Scheduled Time", 30],
		["Ready", 22],
		["Started", 22],
		["Committed", 22],
		["Cycle Time", 20],
		["Delta Time", 20],
		["MC Time", 20],
		["Ref Time", 20],
	]);
	const rows: string[][] = [];
	let lastStart: number | null = null;
	for (const e of matchesForLevel(state, level)) {
		const startedIso = e.actualStartTime;
		const startedMs = startedIso ? Date.parse(startedIso) : NaN;
		const scheduledMs = Date.parse(e.scheduledStartTime);
		const hasStart = !Number.isNaN(startedMs);
		// The store does not retain FieldReadyAt / ScoreCommittedAt, so Ready / Committed and the
		// MC-time / Ref-time deltas derived from them are left blank (documented gap).
		const cycleTime = hasStart && lastStart !== null ? goDuration(Math.round((startedMs - lastStart) / 1000)) : "";
		const deltaTime =
			hasStart && !Number.isNaN(scheduledMs) ? goDuration(Math.round((startedMs - scheduledMs) / 1000)) : "";
		rows.push([
			shortName(e.level, e.matchNumber),
			fmtMonthDayClock(e.scheduledStartTime),
			"",
			fmtClock(startedIso),
			"",
			cycleTime,
			deltaTime,
			"",
			"",
		]);
		lastStart = hasStart ? startedMs : null;
	}
	return pdfResponse(
		tablePdf(`${levelTypeName(level)} Cycle Time - ${state.event.name}`, cols, rows, generatedFooter()),
	);
}

function couponsPdf(state: FmsState): Response {
	// CA draws two graphic coupons (VAR + Backup) per playoff alliance; we render the same data as a
	// table. Fall back to CA's default of 8 alliances when none have been created.
	const num = state.alliances.length > 0 ? state.alliances.length : 8;
	const cols = columns([
		["Coupon", 60],
		["Alliance", 30],
	]);
	const rows: string[][] = [];
	for (let i = 1; i <= num; i++) {
		rows.push(["VAR Coupon", String(i)]);
		rows.push(["Backup Coupon", String(i)]);
	}
	return pdfResponse(tablePdf(`Playoff Coupons - ${state.event.name}`, cols, rows));
}

/** Best-effort finals outcome: which alliance won the best-of-3 finals (matches 14-16). */
function finalsResult(state: FmsState): { winner: number | null; finalist: number | null } {
	const wins = new Map<number, number>();
	let redAlliance: number | null = null;
	let blueAlliance: number | null = null;
	for (const n of [14, 15, 16]) {
		const m = state.playoffMatches[n];
		if (!m || !m.complete) continue;
		if (m.red) redAlliance = m.red;
		if (m.blue) blueAlliance = m.blue;
		const winnerAlliance = m.winner === "Red" ? m.red : m.winner === "Blue" ? m.blue : null;
		if (winnerAlliance) wins.set(winnerAlliance, (wins.get(winnerAlliance) ?? 0) + 1);
	}
	let winner: number | null = null;
	for (const [alliance, count] of wins) {
		if (count >= 2) winner = alliance;
	}
	if (winner === null) return { winner: null, finalist: null };
	const finalist = winner === redAlliance ? blueAlliance : redAlliance;
	return { winner, finalist };
}

function alliancesPdf(state: FmsState): Response {
	const cols = columns([
		["Alliance", 23],
		["Team", 12],
		["Name", 80],
		["Location", 80],
	]);
	const { winner, finalist } = finalsResult(state);
	const rows: string[][] = [];
	for (const a of state.alliances) {
		const status = a.allianceNumber === winner ? "Winner" : a.allianceNumber === finalist ? "Finalist" : "";
		const members = [a.captainTeamNumber, a.firstRoundTeamNumber, a.secondRoundTeamNumber, a.alternateTeamNumber]
			.map((n) => n ?? 0)
			.filter((n) => n > 0);
		members.forEach((teamNumber, idx) => {
			const label = idx === 0 ? `Alliance ${a.allianceNumber}${status ? ` (${status})` : ""}` : "";
			rows.push([label, String(teamNumber), teamName(state, teamNumber), ", , "]);
		});
	}
	return pdfResponse(tablePdf(`Playoff Alliances - ${state.event.name}`, cols, rows, generatedFooter()));
}

function bracketPdf(state: FmsState): Response {
	// CA serves the bracket as an SVG-bearing HTML page for the browser to print to PDF; the emulator
	// renders the same matchup data directly as a PDF table.
	const cols = columns([
		["Match", 25],
		["Red Alliance", 40],
		["Blue Alliance", 40],
		["Score", 30],
	]);
	const allianceLabel = (allianceNumber: number | null, teams: readonly number[]): string => {
		if (allianceNumber) return `Alliance ${allianceNumber}`;
		const filled = teams.filter((n) => n > 0);
		return filled.length ? filled.join(", ") : "";
	};
	const rows = matchesForLevel(state, "Playoff").map((e) => [
		shortName(e.level, e.matchNumber),
		allianceLabel(e.redAllianceNumber, e.red),
		allianceLabel(e.blueAllianceNumber, e.blue),
		e.status === "Played" ? `${e.finalScoreRed ?? 0} - ${e.finalScoreBlue ?? 0}` : "",
	]);
	return pdfResponse(tablePdf(`Playoff Bracket - ${state.event.name}`, cols, rows, generatedFooter()));
}

function judgingSchedulePdf(state: FmsState): Response {
	// The store has no judging slots, so both CA tables (team view + judges' view) render empty.
	const teamCols = columns([
		["Team", 25],
		["Judging Time", 50],
		["Previous Match", 60],
		["Next Match", 60],
	]);
	// Render as one titled table with no rows; the judges'-view header is included as a footer marker.
	return pdfResponse(
		tablePdf(
			`Judging Schedule - ${state.event.name}`,
			teamCols,
			[],
			`Judging Schedule (Judges' View) - ${state.event.name}    ${generatedFooter()}`,
		),
	);
}

// #endregion

// #region entry point

/**
 * Handle a Cheesy Arena `/reports/*` request, reading the fake-fms store. Returns a Response for a
 * recognised report route (CSV or PDF), or null when the path is not a report route.
 */
export function handleCaReports(store: FmsStore, url: URL): Response | null {
	const p = url.pathname;
	if (!p.startsWith("/reports/")) return null;
	const state = store.getState();

	// CSV routes.
	switch (p) {
		case "/reports/csv/backups":
			return backupsCsv(state);
		case "/reports/csv/fta":
			return ftaCsv(state);
		case "/reports/csv/rankings":
			return rankingsCsv(state);
		case "/reports/csv/teams":
			return teamsCsv(state);
		case "/reports/csv/wpa_keys":
			return wpaKeysCsv(state);
	}
	const scheduleCsvMatch = p.match(/^\/reports\/csv\/schedule\/([A-Za-z]+)$/);
	if (scheduleCsvMatch) {
		const level = TYPE_LEVELS[(scheduleCsvMatch[1] ?? "").toLowerCase()];
		if (!level) return serverError(`invalid match type "${scheduleCsvMatch[1]}"`);
		return scheduleCsv(state, level);
	}

	// PDF routes.
	switch (p) {
		case "/reports/pdf/alliances":
			return alliancesPdf(state);
		case "/reports/pdf/backups":
			return backupsPdf(state);
		case "/reports/pdf/bracket":
			return bracketPdf(state);
		case "/reports/pdf/coupons":
			return couponsPdf(state);
		case "/reports/pdf/judging_schedule":
			return judgingSchedulePdf(state);
		case "/reports/pdf/rankings":
			return rankingsPdf(state);
		case "/reports/pdf/teams":
			return teamsPdf(state);
	}
	const cycleMatch = p.match(/^\/reports\/pdf\/cycle\/([A-Za-z]+)$/);
	if (cycleMatch) {
		const level = TYPE_LEVELS[(cycleMatch[1] ?? "").toLowerCase()];
		if (!level) return serverError(`invalid match type "${cycleMatch[1]}"`);
		return cyclePdf(state, level);
	}
	const schedulePdfMatch = p.match(/^\/reports\/pdf\/schedule\/([A-Za-z]+)$/);
	if (schedulePdfMatch) {
		const level = TYPE_LEVELS[(schedulePdfMatch[1] ?? "").toLowerCase()];
		if (!level) return serverError(`invalid match type "${schedulePdfMatch[1]}"`);
		return schedulePdf(state, level);
	}

	return null;
}

// #endregion
